[project]
name = "ask-and-answer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "azure-identity>=1.23.1",
    "msal>=1.33.0",
    "openai-agents>=0.2.3",
    "pymongo>=4.13.2",
]
